### ISSUE TITLE
getStoredQueue assert failure

### ISSUE THREAD

**Issue by emmettbutler** [Parsely/parsely-android#30]
There's an [assert statement](https://github.com/Parsely/parsely-android/blob/8342f01aa04c1e47c90421f517916c419471e998/parsely/parselyandroid/ParselyTracker.java#L529) in the SDK's init logic that has been shown to fail occasionally.
```
2021-06-11 11:25:48.793 12729-12729/com.xxx.android.xxx E/ParselyWrapper: Error
java.lang.AssertionError
at com.parsely.parselyandroid.ParselyTracker.getStoredQueue(ParselyTracker.java:530)
at com.parsely.parselyandroid.ParselyTracker.(ParselyTracker.java:100)
at com.parsely.parselyandroid.ParselyTracker.sharedInstance(ParselyTracker.java:136)
at com.parsely.parselyandroid.ParselyTracker.sharedInstance(ParselyTracker.java:124)
at com.xxx.android.app.ads_analytics.ParselyWrapper.initialize(ParselyWrapper.kt:22)
at com.xxx.android.app.application.Application.initParsely(Application.kt:335)
at com.xxx.android.app.application.Application.onCreate(Application.kt:113)
```

The assertion should probably be removed.

**Comment by wzieba** [comment]
This issue has been addressed in https://github.com/Parsely/parsely-android/pull/31
