### ISSUE TITLE
NullPointerException when accessing deviceInfo map in ParselyTracker.java

### ISSUE THREAD

**Issue by rafayali** [Parsely/parsely-android#57]
When using 3.0.6 version of SDK, our app is reporting crashes due to `deviceInfo` map not being initialized when accessing its entries when calling `ParselyTracker.trackPageView`. Below is a stacktrace from crashlytics:

Android 13
Parsley SDK 3.0.6

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
       at com.parsely.parselyandroid.ParselyTracker.buildEvent(ParselyTracker.java:404)
       at com.parsely.parselyandroid.ParselyTracker.trackPageview(ParselyTracker.java:234)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:68)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
       at android.view.Choreographer.doCallbacks(Choreographer.java:923)
       at android.view.Choreographer.doFrame(Choreographer.java:847)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

**Comment by wzieba** [comment]
Thank you for the report @rafayali ! We're working on it 👍

**Comment by wzieba** [comment]
The SDK in version https://github.com/Parsely/parsely-android/releases/tag/3.0.7 fixes this issue and is now available at Maven Central

**Comment by rafayali** [comment]
Thanks @wzieba and team!
